base_local_planner: base_local_planner/TrajectoryPlannerROS

TrajectoryPlannerROS:
  max_vel_x: 0.45
  #min_vel_x: 0.05
  #max_vel_theta: 1.0
  
  #min_in_place_vel_theta: 0.4
  #acc_lim_x: 0.005
  #acc_lim_y: 0.005
  #acc_lim_theta: 0.005
  dwa: false
  holonomic_robot: true
  